#include <GL/glew.h>
#include <GL/freeglut.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "util.h"

/* The dimensions of the window. */
#define WINDOW_WIDTH 800
#define WINDOW_HEIGHT 600

/* Defines the size of the buffer used to store error logs, for example logs
 * generated by the driver in response to glsl compiler or linker errors. */
#define ERROR_LOG_LENGTH 200

/* Loads the contents of a file into a buffer.
 * Parameters:
 *   file_name: A pointer to a string that is the name of the file.
 * Returns:
 *   A buffer that is the length of the file plus one that contains the contents
 *   of the file and a null-terminator at the end. */
static char *
load_file (char *file_name)
{
  FILE *file;
  size_t size_in_bytes;
  char *file_contents;

  file = fopen (file_name, "rb");

  /* Get the file length in bytes. */
  fseek (file, 0, SEEK_END);
  size_in_bytes = ftell (file);

  /* Add one for the null-terminator. */
  file_contents = (char *) malloc ((size_in_bytes + sizeof (char)) * sizeof (char));

  /* Rewind the file pointer and read the file into the buffer. */
  rewind (file);
  fread (file_contents, sizeof(char), size_in_bytes, file);

  file_contents[size_in_bytes] = '\0';
  fclose (file);

  return file_contents;
}

/* Attempts to load, compile and link a vertex shader and a fragment shader into
 * a program for OpenGL to use. If these operations are unsuccessful, the
 * program will terminate with an error message. The vertex shader must be
 * called vertex_shader.glsl and the fragment shader must be called
 * fragment_shader.glsl. */
static void
init_shaders ()
{
  /* Load the shader source into buffers. */
  const GLchar *vertex_shader_source = (GLchar *) load_file ("vertex_shader.glsl");
  const GLchar *fragment_shader_source = (GLchar *) load_file ("fragment_shader.glsl");

  GLuint vertex_shader, fragment_shader;
  GLint compilation_successful, link_successful, compiler_log_length,
        linker_log_length;

  /* Get IDs from OpenGL for the shader objects. */
  vertex_shader = glCreateShader (GL_VERTEX_SHADER);
  fragment_shader = glCreateShader (GL_FRAGMENT_SHADER);

  /* Give the shader source to the GPU. */
  glShaderSource (vertex_shader, 1, &vertex_shader_source, NULL);
  glShaderSource (fragment_shader, 1, &fragment_shader_source, NULL);

  /* Attempt compilation of the shaders. */
  glCompileShader (vertex_shader);
  glCompileShader (fragment_shader);

  /* Check to see whether the vertex shader compiled. */
  glGetObjectParameterivARB (vertex_shader, GL_COMPILE_STATUS,
                             &compilation_successful);
  if (!compilation_successful) {
    printf ("Compilation of the vertex shader did not succeed. Exiting.\n");
    GLchar compiler_log[ERROR_LOG_LENGTH];
    glGetShaderInfoLog (vertex_shader, ERROR_LOG_LENGTH, &compiler_log_length,
                        compiler_log);
    printf ("%s", compiler_log);
    exit (EXIT_FAILURE);
  }

  /* Check to see whether the fragment shader compiled. */
  glGetObjectParameterivARB (fragment_shader, GL_COMPILE_STATUS,
                          &compilation_successful);
  if (!compilation_successful) {
    printf ("Compilation of the fragment shader did not succeed. Exiting.\n");
    printf ("%s\n", fragment_shader_source);
    GLchar compiler_log[ERROR_LOG_LENGTH];
    glGetShaderInfoLog (fragment_shader, ERROR_LOG_LENGTH, &compiler_log_length, compiler_log);
    printf ("%s", compiler_log);
    exit (EXIT_FAILURE);
  }

  /* Create a program object and attempt to attach and link the shaders. */
  program_object = glCreateProgram ();
  glAttachShader (program_object, vertex_shader);
  glAttachShader (program_object, fragment_shader);
  glLinkProgram (program_object);

  /* Check whether the shaders linked successfully. */
  glGetProgramiv (program_object, GL_LINK_STATUS, &link_successful);
  if (!link_successful) {
    printf ("Link of the shaders did not succeed. Exiting.\n");
    GLchar linker_log[ERROR_LOG_LENGTH];
    glGetProgramInfoLog (program_object, ERROR_LOG_LENGTH, &linker_log_length,
                         linker_log);
    printf ("%s", linker_log);
    exit (EXIT_FAILURE);
  }

  /* Tell OpenGL to use this shader object for future draw calls. */
  glUseProgram (program_object);
}

void
init (int *argc, char **argv, char *window_title)
{
  glutInit (argc, argv);
  glutInitWindowSize (WINDOW_WIDTH, WINDOW_HEIGHT);
  glutInitDisplayMode (GLUT_RGB | GLUT_DOUBLE | GLUT_DEPTH);
  glutCreateWindow (window_title);
 
  glewInit ();

  init_shaders ();

  glClearColor (0.0f, 0.0f, 0.0f, 1.0f);
}

